import './globals.css'
import { Inter } from 'next/font/google'

import MuiNavbar from '@/components/layouts/Navbar/Navbar';
import  GlobalProvider from "@/app/GlobalProvider"
import { CartProvider } from '@/context/CartContext';
import { AuthProvider } from '@/context/AuthContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
      <AuthProvider>
      <CartProvider>
      <MuiNavbar/>
      {children}
      </CartProvider>
      </AuthProvider>
      </body>
    </html>
  )
}
