import './globals.css'
import { Inter } from 'next/font/google'

import MuiNavbar from '@/components/layouts/Navbar/Navbar';
import  {GlobalProvider} from "@/app/GlobalProvider"
import { CartProvider } from '@/context/CartContext';
import { AuthProvider } from '@/context/AuthContext';

// import {newsProvider} from "@/context/NewsContext"
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';






const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head/>
    <body className={inter.className}>
   
      <ToastContainer position='bottom-right'/>

      <AuthProvider>
      <CartProvider>
      <MuiNavbar/>
      {children}
      </CartProvider>
  </AuthProvider>

     

      </body>
    </html>
  )
}
